import Head from "next/head";
import classes from "../styles/Home.module.scss";
import LinkButton from "../components/Button/Button";
import BallonSVG from "../components/BallonSVG/Ballon";
import Bar from "../components/Bars/Bar";
import ProjectsContainer from "../components/Projects/Container";
import { projects } from "../data/projects";
import { tech } from "../data/tech";
import { jsonify } from "../middleware/jsonify";
import { dateFromNow } from "../middleware/dateFromNow";
export default function Home(props) {
  const { projects, basic, advanced, lookingF } = props;
  return (
    <div>
      <Head>
        <title>Dwave | Dusan Djordjic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.mainContainer}>
        <section className={`${classes.introSec} ${classes.section}`}>
          <div className={classes.content}>
            <h1>
              Welcome To <br /> My Personal Portoflio
            </h1>
            <p className={classes.darkerText}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Consequuntur quod harum molestias ipsam deserunt officiis optio
              iusto voluptas? Suscipit, provident?
            </p>
            <LinkButton text={"Learn more"} link="https://www.google.com/" />
          </div>
          <div className={classes.introSecImg}>
            <BallonSVG />
          </div>
        </section>
        <section
          className={`${classes.projectsSec} ${classes.section}`}
          id="projects"
        >
          <div className={classes.secTitle}>
            <Bar />
            <h2>Projects</h2>
          </div>
          <div className={classes.projectsConteiner}>
            <ProjectsContainer projects={projects} />
          </div>
        </section>
        <section className={`${classes.techSec} ${classes.section}`} id="tech">
          <div className={classes.secTitle}>
            <Bar />
            <h2>Technologies</h2>
          </div>
          <div className={classes.techContainer}>
            <div className={`${classes.techs} ${classes.techsBasic}`}>
              <div className={classes.techHeader}>
                <h3>Basic knowledge of:</h3>
              </div>
              {basic.map((item, index) => {
                return (
                  <div
                    key={index}
                    className={`${classes.techItem} ${classes.techItemBasic}`}
                  >
                    <h4>{item.name}</h4>
                    <p>
                      <span>{dateFromNow(item.time)}</span> months
                    </p>
                  </div>
                );
              })}
            </div>

            <div className={`${classes.techs} ${classes.techsAdvanced}`}>
              <div className={classes.techHeader}>
                <h3>Advanced knowledge of:</h3>
              </div>
              {advanced.map((item, index) => {
                return (
                  <div
                    key={index}
                    className={`${classes.techItem} ${classes.techItemAdvanced}`}
                  >
                    <h4>{item.name}</h4>
                    <p>
                      <span>{dateFromNow(item.time)}</span> months
                    </p>
                  </div>
                );
              })}
            </div>

            <div className={`${classes.techs} ${classes.techsLookingF}`}>
              <div className={classes.techHeader}>
                <h3>Looking Forward To Learn:</h3>
              </div>
              {lookingF.map((item, index) => {
                return (
                  <div
                    key={index}
                    className={`${classes.techItem} ${classes.techItemLookingF}`}
                  >
                    <h4>{item.name}</h4>
                    <p>
                      <span>0</span> months
                    </p>
                  </div>
                );
              })}
            </div>
            {/* <TechContainer tech={tech} /> */}
          </div>
        </section>
        <section
          className={`${classes.aboutSec} ${classes.section}`}
          id="about"
        >
          <div className={classes.secTitle}>
            <Bar />
            <h2>About me</h2>
          </div>
        </section>
      </main>
    </div>
  );
}
export const getStaticProps = () => {
  return {
    props: {
      projects: projects,
      basic: jsonify(
        tech.filter((item) => {
          return item.level === 1;
        })
      ),
      advanced: jsonify(
        tech.filter((item) => {
          return item.level === 2;
        })
      ),
      lookingF: jsonify(
        tech.filter((item) => {
          return item.level === 0;
        })
      ),
    },
  };
};
