import Head from "next/head";
import Image from "next/image";
import classes from "../styles/Home.module.scss";
import LinkButton from "../components/Button/Button";
import BallonSVG from "../components/BallonSVG/Ballon";
import Bar from "../components/Bars/Bar";
import ProjectsContainer from "../components/Projects/Container";
import { projects } from "../data/projects";
import { tech } from "../data/tech";
import { jsonify } from "../middleware/jsonify";
import TechContainer from "../components/Techs/TechContainer";
import AboutContainer from "../components/About/AboutContainer";
import BrandContainer from "../components/Brand/BrandContainer";
export default function Home(props) {
  const { projects, basic, advanced, lookingF } = props;
  return (
    <div>
      <Head>
        <title>Dusan Djordjic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.mainContainer}>
        <section className={`${classes.introSec} ${classes.section}`}>
          <div className={classes.content}>
            <h1>
              Welcome To <br /> My Personal Portoflio
            </h1>
            <p className={classes.darkerText}>
              Hey there, I hope we can get to know each other and work together
              on some cool web apps
            </p>
            <LinkButton text={"Learn more"} link="/#about" />
          </div>
          <div className={classes.introSecImg}>
            <BallonSVG />
          </div>
        </section>
        <section
          className={`${classes.projectsSec} ${classes.section}`}
          id="projects"
        >
          <div className={classes.secTitle}>
            <Bar />
            <h2>Projects</h2>
          </div>
          <div className={classes.projectsConteiner}>
            <ProjectsContainer projects={projects} />
          </div>
        </section>
        <section className={`${classes.techSec} ${classes.section}`} id="tech">
          <div className={classes.secTitle}>
            <Bar />
            <h2>Technologies</h2>
          </div>
          <TechContainer
            data={[
              { techs: basic, type: "basic" },
              { techs: advanced, type: "advanced" },
              { techs: lookingF, type: "lookingf" },
            ]}
          />
        </section>
        <section
          className={`${classes.aboutSec} ${classes.section}`}
          id="about"
        >
          <div className={classes.secTitle}>
            <Bar />
            <h2>About me</h2>
          </div>
          <AboutContainer />
        </section>
      </main>
    </div>
  );
}
export const getStaticProps = () => {
  return {
    props: {
      projects: projects,
      basic: jsonify(
        tech.filter((item) => {
          return item.level === 1;
        })
      ),
      advanced: jsonify(
        tech.filter((item) => {
          return item.level === 2;
        })
      ),
      lookingF: jsonify(
        tech.filter((item) => {
          return item.level === 0;
        })
      ),
    },
  };
};
